# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28d7320f17ba7243ebd5ad6c5bdde5fba03c556c5db23a455ee120c48ab527cb2ffd3b32db04a35221eef4d0bee98ab2d19e4ec2e4ec97699cc5ae20de46ff08

test:
  secret_key_base: b6e4838b7ffea0e32be3256c7c59f26e31cb87be9a69be2f42d4d08ffeb4f9e69d892b03bdb4b6f064d8cf9785215f6c5091ee928f9e1fad3446f2005eedbbb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
