# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9535b63d1620669393d2351e5f9187a4268a4bbb9db42d99d4b0b9a76b35215e7352b30e9dc449badbc845a39ccfe125990cd38026100f2a80497cec3b5048

test:
  secret_key_base: 9c7c8f27a843d72de9a2686bcecaba8e233477e466bebcdd74c48459186cd48e267695aeb9c224ca8cd3f16f79e276858e21da8acf07eb7637d6e83fabab26ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
